Icasie/Controllers/FormatCheckerController.cs
using Icasie.Helper;
using Icasie.Models;
using Icasie.Repositories;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Icasie.Controllers
{
    [Authorize(Roles = "Format Checker, Administrator")]
    public class FormatCheckerController : Controller
    {
        public ActionResult Index(int id)
        {
            List<ViewModelConference> confList = new List<ViewModelConference>();
            //get user credential
            string currentUserEmail = HttpContext.User.Identity.Name;

            using (IcasieEntities entity = new IcasieEntities())
            {
                var conference = entity.Conferences.Where(c => c.ConferenceId == id).ToList();

                var subThemes = entity.SubThemes.ToList();

                var formatChecker = entity.Users.SingleOrDefault(c => c.Email == currentUserEmail);

                foreach (var item in conference)
                {
                    ViewModelConference newConf = new ViewModelConference();
                    newConf.PaperSubActive = false;

                    if (item.PaperSubStartDate <= DateTime.Now && item.PaperSubEndDate >= DateTime.Now)
                    {
                        newConf.PaperSubActive = true;
                    }

                    //fill the properties
                    newConf.ConferenceId = item.ConferenceId;
                    newConf.Name = item.Name;
                    newConf.StartDate = item.StartDate;
                    newConf.EndDate = item.EndDate;
                    newConf.PaperSubStartDate = item.PaperSubStartDate;
                    newConf.PaperSubEndDate = item.PaperSubEndDate;
                    newConf.Submissions = new List<ViewModelSubmission>();

                    var submissions = entity.Submissions.Where(c => c.ConferenceId == item.ConferenceId && c.FormatCheckerId == formatChecker.UserId && (c.FullPaperStatus == Constant.FullPaperStatus.PaymentVerified || c.FullPaperStatus == Constant.FullPaperStatus.FormatRevised));
                    foreach (var subItem in submissions)
                    {
                        ViewModelSubmission newSubmission = new ViewModelSubmission();
                        newSubmission.UserId = subItem.UserId;

                        var user = entity.Users.SingleOrDefault(c => c.UserId == newSubmission.UserId);

                        newSubmission.AuthorName = user.FirstName + " " + user.LastName;
                        newSubmission.ConferenceId = subItem.ConferenceId;
                        newSubmission.FullPaperStatus = subItem.FullPaperStatus;
                        newSubmission.FullPaper = subItem.FullPaper;
                        newSubmission.FullPaperDate = subItem.FullPaperDate;
                        newSubmission.FullPaperFileName = subItem.FullPaperFileName;
                        newSubmission.Title = subItem.Title;
                        newSubmission.SubmissionId = subItem.SubmissionId;
                        newSubmission.Number = subItem.PaperNumber;
                        newSubmission.SubThemesId = subItem.SubThemesId;
                        newSubmission.SubThemes = subThemes.FirstOrDefault(c => c.SubThemesId == subItem.SubThemesId).Title;


                        if (subItem.FormatCheckerId != null)
                        {
                            var formatCheckerId = entity.Users.SingleOrDefault(c => c.UserId == subItem.FormatCheckerId);
                            newSubmission.FormatCheckerName = formatCheckerId.FirstName + " " + formatCheckerId.LastName;
                            newSubmission.FormatCheckingResultFileName = subItem.FormatCheckingResultFileName;
                        }


                        newSubmission.FormatCheckingDateString = subItem.FormatCheckingDate.HasValue ? subItem.FormatCheckingDate.Value.ToString(Constant.DateFormat) : string.Empty;

                        newConf.Submissions.Add(newSubmission);
                    }

                    confList.Add(newConf);

                }


            }
            return View(confList);
        }

        public ActionResult Edit(int id) {
            ViewModelSubmission sub = new ViewModelSubmission();
            using (IcasieEntities entity = new IcasieEntities())
            {
                var oldSub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                sub.SubmissionId = oldSub.SubmissionId;
                sub.ConferenceId = oldSub.ConferenceId;
                sub.Title = oldSub.Title;
            }
            return View(sub);
        }

        [HttpPost]
        public ActionResult Edit(int id, string fullPaperStatus, string comment, HttpPostedFileBase file)
        {
            int conferenceId = 0;
            if (fullPaperStatus == Constant.FullPaperStatus.FormatRevised && file == null)
            {
                ModelState.AddModelError("file", "File cannot be empty");
            }

            if (fullPaperStatus == Constant.FullPaperStatus.FormatRevised)
            {
                if (comment == null || comment == string.Empty)
                {
                    ModelState.AddModelError("comment", "Comment is required");
                }
            }

            if (!ModelState.IsValid)
            {
                ViewModelSubmission sub = new ViewModelSubmission();
                using (IcasieEntities entity = new IcasieEntities())
                {
                    var oldSub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                    sub.SubmissionId = oldSub.SubmissionId;
                    sub.Title = oldSub.Title;
                    sub.FullPaperStatus = fullPaperStatus;
                    sub.Comment = comment;
                }

                return View(sub);
            }

            try
            {
                using (IcasieEntities entity = new IcasieEntities())
                {
                    var sub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                    sub.Comment = comment;
                    sub.FullPaperStatus = fullPaperStatus;
                    conferenceId = sub.ConferenceId;

                    sub.FormatCheckingDate = DateTime.Now;

                    string currentUserEmail = HttpContext.User.Identity.Name;

                    int userId = entity.Users.SingleOrDefault(c => c.Email == currentUserEmail).UserId;

                    sub.FormatCheckerId = userId;

                    if (fullPaperStatus == Constant.FullPaperStatus.FormatChecked)
                    {
                        sub.FormatCheckingResult = null;
                        sub.FormatCheckingResultFileName = null;

                        var conferenceName = entity.Conferences.SingleOrDefault(c => c.ConferenceId == sub.ConferenceId).Name;
                        var title = sub.Title;
                        List<string> reviewerEmail = new List<string>();

                        reviewerEmail.Add(entity.Users.SingleOrDefault(c => c.UserId == sub.ReviewedBy).Email);
                        Task.Run(() => Helper.EmailHelper.SendEmailNotification(reviewerEmail, Constant.NotificationMode.AssignReviewer, conferenceName, title));
                    }
                    else
                    {

                        if (file != null)
                        {
                            using (Stream inputStream = file.InputStream)
                            {
                                MemoryStream memoryStream = inputStream as MemoryStream;
                                if (memoryStream == null)
                                {
                                    memoryStream = new MemoryStream();
                                    inputStream.CopyTo(memoryStream);
                                }
                                sub.FormatCheckingResult = memoryStream.ToArray();
                                sub.FormatCheckingResultFileName = file.FileName;
                            }
                        }


                    }


                    entity.SaveChanges();
                }
            }
            catch (DbEntityValidationException ex)
            {
            }


            return RedirectToAction("Index", new { id = conferenceId });
        }
	}
}

Icasie/Views/FormatChecker/Edit.cshtml
@model Icasie.Models.ViewModelSubmission

@{
    ViewBag.Title = "Review Full Paper";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Proof Read Paper</h2>


@using (Html.BeginForm("Edit", "FormatChecker", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Model.Title
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Status", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FullPaperStatus", Icasie.Helper.Helper.GetFormatCheckingStatusList(), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FullPaperStatus)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Upload Format Checking Review Result", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file">
                    <input accept="application/pdf" name="file" id="file" type="file" />
                </label>
                <br />@Html.ValidationMessage("file")
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Comment, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comment, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Comment)
            </div>
        </div>
        @Html.Hidden("id", Model.SubmissionId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.ConferenceId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Icasie/Views/FormatChecker/Index.cshtml
@model IEnumerable<Icasie.Models.ViewModelConference>

@{
    ViewBag.Title = "Review List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1>Proof Reads</h1>
</div>


@foreach (var item in Model)
{
    <div class="row">
        <h3>@item.Name</h3>
        <table class="table table-result">
            <thead>
                <tr>
                    <th>
                        Author
                    </th>
                    <th>
                        Number
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Sub Theme
                    </th>
                    <th>
                        Full Paper
                    </th>
                    <th>
                        Full Paper Upload Date
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Format Checking Result
                    </th>
                    <th>
                        Format Checker
                    </th>
                    <th>
                        Format Checking Date
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr>

                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                </tr>
            </tfoot>
            <tbody>
                @foreach (var abs in item.Submissions)
                {
                    <tr>
                        <td>@abs.AuthorName</td>
                        <td>@abs.Number</td>
                        <td>@abs.Title</td>
                        <td>@abs.SubThemes</td>
                        <td><a class="btn btn-primary" href="/Submission/Download/@abs.SubmissionId?type=@Icasie.Helper.Constant.DownloadType.FullPaper">View</a></td>
                        <td>@abs.FullPaperDate.Value.ToString(Icasie.Helper.Constant.DateFormat)</td>
                        <td>@abs.FullPaperStatus</td>
                        <td>@((abs.FormatCheckingResultFileName != null) ? Html.ActionLink("View", "Download", "Submission", new { @id = abs.SubmissionId, @type = Icasie.Helper.Constant.DownloadType.FormatChecking }, new { @class = "btn btn-primary" }) : Html.Raw(""))</td>
                        <td>@abs.FormatCheckerName</td>
                        <td>@abs.FormatCheckingDateString</td>
                        <td>
                            @if (abs.FullPaperStatus.Equals(Icasie.Helper.Constant.FullPaperStatus.PaymentVerified))
                            {
                                <a class="btn btn-warning" href="/FormatChecker/Edit/@abs.SubmissionId">Format Check</a>
                            }
                        </td>
                    </tr>
                }

            </tbody>

        </table>

    </div>
}

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.table-result').DataTable({
                initComplete: function () {
                    this.api().columns().every(function (index) {
                        if (index == 6) {
                            var column = this;
                            var select = $('<select><option value=""></option></select>')
                                .appendTo($(column.footer()).empty())
                                .on('change', function () {
                                    var val = $.fn.dataTable.util.escapeRegex(
                                        $(this).val()
                                    );

                                    column
                                        .search(val ? '^' + val + '$' : '', true, false)
                                        .draw();
                                });

                            column.data().unique().sort().each(function (d, j) {
                                select.append('<option value="' + d + '">' + d + '</option>')
                            });
                        }

                    });
                }
            });
        });

    </script>
}