Icasie/Controllers/ConferenceController.cs
using Icasie.Helper;
using Icasie.Models;
using Icasie.Repositories;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Icasie.Controllers
{
    [Authorize(Roles = "Reviewer, Proof Reader, Format Checker, Administrator")]
    public class ConferenceController : Controller
    {
        //
        // GET: /Conference/
        public ActionResult Index()
        {
            List<ViewModelConference> results = new List<ViewModelConference>();
            using (IcasieEntities entity = new IcasieEntities())
            {
                var conferences = entity.Conferences.ToList();
                foreach (var item in conferences)
                {
                    ViewModelConference newConf = new ViewModelConference();
                    newConf.PaperSubActive = false;
                    if (item.PaperSubStartDate <= DateTime.Now && item.PaperSubEndDate >= DateTime.Now)
                    {
                        newConf.PaperSubActive = true;
                    }

                    //fill the properties
                    newConf.ConferenceId = item.ConferenceId;
                    newConf.Name = item.Name;
                    newConf.StartDate = item.StartDate;
                    newConf.EndDate = item.EndDate;
                    newConf.PaperSubStartDate = item.PaperSubStartDate;
                    newConf.PaperSubEndDate = item.PaperSubEndDate;

                    results.Add(newConf);
                }
            }
            return View(results);
        }

        public ActionResult Payments()
        {
            List<ViewModelConference> results = new List<ViewModelConference>();
            using (IcasieEntities entity = new IcasieEntities())
            {
                var conferences = entity.Conferences.ToList();
                foreach (var item in conferences)
                {
                    ViewModelConference newConf = new ViewModelConference();
                    newConf.PaperSubActive = false;
                    if (item.PaperSubStartDate <= DateTime.Now && item.PaperSubEndDate >= DateTime.Now)
                    {
                        newConf.PaperSubActive = true;
                    }

                    //fill the properties
                    newConf.ConferenceId = item.ConferenceId;
                    newConf.Name = item.Name;
                    newConf.StartDate = item.StartDate;
                    newConf.EndDate = item.EndDate;
                    newConf.PaperSubStartDate = item.PaperSubStartDate;
                    newConf.PaperSubEndDate = item.PaperSubEndDate;

                    results.Add(newConf);
                }
            }
            return View(results);
        }

        public ActionResult Assign(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            ViewModelConference result = new ViewModelConference();
            using (IcasieEntities entity = new IcasieEntities())
            {
                var conf = entity.Conferences.SingleOrDefault(c => c.ConferenceId == id);
                result.Name = conf.Name;
                result.ConferenceId = conf.ConferenceId;
                result.StartDateString = conf.StartDate.ToString(Constant.DateFormatInput);
                result.EndDateString = conf.EndDate.ToString(Constant.DateFormatInput);
                result.PaperSubStartDateString = conf.PaperSubStartDate.ToString(Constant.DateFormatInput);
                result.PaperSubEndDateString = conf.PaperSubEndDate.ToString(Constant.DateFormatInput);
            }

            return View(result);
        }

        [HttpPost]
        public ActionResult Edit(ViewModelConference model)
        {
            DateTime outStartDate = new DateTime();
            DateTime outEndDate = new DateTime();
            DateTime outPaperStartDate = new DateTime();
            DateTime outPaperEndDate = new DateTime();

            IFormatProvider provider = CultureInfo.CurrentCulture;
            if (!DateTime.TryParseExact(model.StartDateString, Constant.DateFormatInput, provider, DateTimeStyles.None, out outStartDate))
            {
                ModelState.AddModelError("StartDateString", "Start Date format is not valid");
            }

            if (!DateTime.TryParseExact(model.EndDateString, Constant.DateFormatInput, provider, DateTimeStyles.None, out outEndDate))
            {
                ModelState.AddModelError("EndDateString", "End Date format is not valid");
            }

            if (!DateTime.TryParseExact(model.PaperSubStartDateString, Constant.DateFormatInput, provider, DateTimeStyles.None, out outPaperStartDate))
            {
                ModelState.AddModelError("PaperSubStartDateString", "Paper Submission Start Date format is not valid");
            }

            if (!DateTime.TryParseExact(model.PaperSubEndDateString, Constant.DateFormatInput, provider, DateTimeStyles.None, out outPaperEndDate))
            {
                ModelState.AddModelError("PaperSubEndDateString", "Paper Submission End Date format is not valid");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }


            using (IcasieEntities entity = new IcasieEntities())
            {
                var odlConf = entity.Conferences.SingleOrDefault(c => c.ConferenceId == model.ConferenceId);

                odlConf.Name = model.Name;
                odlConf.StartDate = outStartDate;
                odlConf.EndDate = outEndDate;
                odlConf.PaperSubStartDate = outPaperStartDate;
                odlConf.PaperSubEndDate = outPaperEndDate;

                entity.SaveChanges();

            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            bool isExist = false;

            using (IcasieEntities entity = new IcasieEntities())
            {
                isExist = entity.Submissions.Any(c => c.ConferenceId == id);
                if (isExist == false)
                {
                    var conference = entity.Conferences.SingleOrDefault(c => c.ConferenceId == id);

                    entity.Conferences.Remove(conference);
                    entity.SaveChanges();
                }
            }

            if (isExist == true)
            {
                TempData["Message"] = "Conference cannot be deleted";
            }

            return RedirectToAction("index");
        }

        [HttpPost]
        public ActionResult Create(ViewModelConference model)
        {
            DateTime outStartDate = new DateTime();
            DateTime outEndDate = new DateTime();
            DateTime outPaperStartDate = new DateTime();
            DateTime outPaperEndDate = new DateTime();

            IFormatProvider provider = CultureInfo.CurrentCulture;
            if (!DateTime.TryParseExact(model.StartDateString, Constant.DateFormatInput, provider, DateTimeStyles.None, out outStartDate))
            {
                ModelState.AddModelError("StartDateString", "Start Date format is not valid");
            }

            if (!DateTime.TryParseExact(model.EndDateString, Constant.DateFormatInput, provider, DateTimeStyles.None, out outEndDate))
            {
                ModelState.AddModelError("EndDateString", "End Date format is not valid");
            }

            if (!DateTime.TryParseExact(model.PaperSubStartDateString, Constant.DateFormatInput, provider, DateTimeStyles.None, out outPaperStartDate))
            {
                ModelState.AddModelError("PaperSubStartDateString", "Paper Submission Start Date format is not valid");
            }

            if (!DateTime.TryParseExact(model.PaperSubEndDateString, Constant.DateFormatInput, provider, DateTimeStyles.None, out outPaperEndDate))
            {
                ModelState.AddModelError("PaperSubEndDateString", "Paper Submission End Date format is not valid");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }


            using (IcasieEntities entity = new IcasieEntities())
            {
                Conference conference = new Conference();

                var prefix = model.Name.Replace(" ", "");
                prefix = prefix.ToUpper();

                conference.Name = model.Name;
                conference.StartDate = outStartDate;
                conference.EndDate = outEndDate;
                conference.PaperSubStartDate = outPaperStartDate;
                conference.PaperSubEndDate = outPaperEndDate;
                conference.LastSequenceNumber = prefix + "-" + Constant.NumberSuffix;
                conference.LastParticipantNumber = prefix + "-PART-" + Constant.NumberSuffix;

                entity.Conferences.Add(conference);
                entity.SaveChanges();

            }
            return RedirectToAction("Index");
        }
    }
}

Icasie/Controllers/ProofReaderController.cs
using Icasie.Helper;
using Icasie.Models;
using Icasie.Repositories;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Icasie.Controllers
{
    [Authorize(Roles = "Proof Reader, Administrator")]
    public class ProofReaderController : Controller
    {

        public ActionResult Index(int id)
        {
            List<ViewModelConference> confList = new List<ViewModelConference>();
            //get user credential
            string currentUserEmail = HttpContext.User.Identity.Name;

            using (IcasieEntities entity = new IcasieEntities())
            {
                var conference = entity.Conferences.Where(c => c.ConferenceId == id).ToList();

                var subThemes = entity.SubThemes.ToList();

                var proofReaderId = entity.Users.SingleOrDefault(c => c.Email == currentUserEmail);

                foreach (var item in conference)
                {
                    ViewModelConference newConf = new ViewModelConference();
                    newConf.PaperSubActive = false;

                    if (item.PaperSubStartDate <= DateTime.Now && item.PaperSubEndDate >= DateTime.Now)
                    {
                        newConf.PaperSubActive = true;
                    }

                    //fill the properties
                    newConf.ConferenceId = item.ConferenceId;
                    newConf.Name = item.Name;
                    newConf.StartDate = item.StartDate;
                    newConf.EndDate = item.EndDate;
                    newConf.PaperSubStartDate = item.PaperSubStartDate;
                    newConf.PaperSubEndDate = item.PaperSubEndDate;
                    newConf.Submissions = new List<ViewModelSubmission>();

                    var submissions = entity.Submissions.Where(c => c.ConferenceId == item.ConferenceId && c.ProofReaderId == proofReaderId.UserId && (c.FullPaperStatus == Constant.FullPaperStatus.Reviewed || c.FullPaperStatus == Constant.FullPaperStatus.ProofReadingRevised));
                    foreach (var subItem in submissions)
                    {
                        ViewModelSubmission newSubmission = new ViewModelSubmission();
                        newSubmission.UserId = subItem.UserId;

                        var user = entity.Users.SingleOrDefault(c => c.UserId == newSubmission.UserId);

                        newSubmission.AuthorName = user.FirstName + " " + user.LastName;
                        newSubmission.ConferenceId = subItem.ConferenceId;
                        newSubmission.FullPaperStatus = subItem.FullPaperStatus;
                        newSubmission.FullPaper = subItem.FullPaper;
                        newSubmission.FullPaperDate = subItem.FullPaperDate;
                        newSubmission.FullPaperFileName = subItem.FullPaperFileName;
                        newSubmission.Title = subItem.Title;
                        newSubmission.SubmissionId = subItem.SubmissionId;
                        newSubmission.Number = subItem.PaperNumber;
                        newSubmission.SubThemesId = subItem.SubThemesId;
                        newSubmission.SubThemes = subThemes.FirstOrDefault(c => c.SubThemesId == subItem.SubThemesId).Title;


                        if (subItem.ProofReaderId != null)
                        {
                            var proofReader = entity.Users.SingleOrDefault(c => c.UserId == subItem.ProofReaderId);
                            newSubmission.ProofReaderName = proofReader.FirstName + " " + proofReader.LastName;
                            newSubmission.ProofReaderResultFileName = subItem.ProofReadingResultFileName;
                        }


                        newSubmission.ProofReadingDateString = subItem.ProofReadingDate.HasValue ? subItem.ProofReadingDate.Value.ToString(Constant.DateFormat) : string.Empty;

                        newConf.Submissions.Add(newSubmission);
                    }

                    confList.Add(newConf);

                }


            }
            return View(confList);
        }

        public ActionResult Edit(int id)
        {
            ViewModelSubmission sub = new ViewModelSubmission();
            using (IcasieEntities entity = new IcasieEntities())
            {
                var oldSub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                sub.SubmissionId = oldSub.SubmissionId;
                sub.ConferenceId = oldSub.ConferenceId;
                sub.Title = oldSub.Title;
            }
            return View(sub);
        }

        [HttpPost]
        public ActionResult Edit(int id, string fullPaperStatus, string comment, HttpPostedFileBase file)
        {
            int conferenceId = 0;
            if (fullPaperStatus == Constant.FullPaperStatus.ProofReadingRevised && file == null)
            {
                ModelState.AddModelError("file", "File cannot be empty");
            }

            if (fullPaperStatus == Constant.FullPaperStatus.ProofReadingRevised)
            {
                if (comment == null || comment == string.Empty)
                {
                    ModelState.AddModelError("comment", "Comment is required");
                }
            }

            if (!ModelState.IsValid)
            {
                ViewModelSubmission sub = new ViewModelSubmission();
                using (IcasieEntities entity = new IcasieEntities())
                {
                    var oldSub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                    sub.SubmissionId = oldSub.SubmissionId;
                    sub.Title = oldSub.Title;
                    sub.FullPaperStatus = fullPaperStatus;
                    sub.Comment = comment;
                }

                return View(sub);
            }

            try
            {
                using (IcasieEntities entity = new IcasieEntities())
                {
                    var sub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                    sub.Comment = comment;
                    sub.FullPaperStatus = fullPaperStatus;
                    conferenceId = sub.ConferenceId;

                    sub.ProofReadingDate = DateTime.Now;

                    string currentUserEmail = HttpContext.User.Identity.Name;

                    int userId = entity.Users.SingleOrDefault(c => c.Email == currentUserEmail).UserId;

                    sub.ProofReaderId = userId;

                    if (fullPaperStatus == Constant.FullPaperStatus.Accepted)
                    {
                        sub.ProofReadingResult = null;
                        sub.ProofReadingResultFileName = null;
                    }
                    else
                    {

                        if (file != null)
                        {
                            using (Stream inputStream = file.InputStream)
                            {
                                MemoryStream memoryStream = inputStream as MemoryStream;
                                if (memoryStream == null)
                                {
                                    memoryStream = new MemoryStream();
                                    inputStream.CopyTo(memoryStream);
                                }
                                sub.ProofReadingResult = memoryStream.ToArray();
                                sub.ProofReadingResultFileName = file.FileName;
                            }
                        }


                    }


                    entity.SaveChanges();
                }
            }
            catch (DbEntityValidationException ex)
            {
            }


            return RedirectToAction("Index", new { id = conferenceId });
        }

    }
}

Icasie/Views/Conference/Create.cshtml
@model Icasie.Models.ViewModelConference

@{
    ViewBag.Title = "Add New Conference";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add New Conference</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        
        <div class="form-group">
            @Html.Label("Name", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" }, })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Start Date", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.StartDateString, new { htmlAttributes = new { @class = "datepicker form-control" }, })
                @Html.ValidationMessageFor(model => model.StartDate)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("End Date", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.EndDateString, new { htmlAttributes = new { @class = "datepicker form-control" }, })
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Paper Submission Start Date", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PaperSubStartDateString, new { htmlAttributes = new { @class = "datepicker form-control" }, })
                @Html.ValidationMessageFor(model => model.PaperSubStartDate)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Paper Submission End Date", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PaperSubEndDateString, new { htmlAttributes = new { @class = "datepicker form-control" }, })
                @Html.ValidationMessageFor(model => model.PaperSubEndDate)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-4 col-md-8">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $.fn.datepicker.defaults.format = "dd-mm-yyyy";
            $('.datepicker').datepicker();
        });
    </script>
}

Icasie/Views/Conference/Edit.cshtml
@model Icasie.Models.ViewModelConference

@{
    ViewBag.Title = "Edit Conference";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Conference</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ConferenceId)
        <div class="form-group">
            @Html.Label("Name", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" }, })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Start Date", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.StartDateString, new { htmlAttributes = new { @class = "datepicker form-control" }, })
                @Html.ValidationMessageFor(model => model.StartDate)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("End Date", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.EndDateString, new { htmlAttributes = new { @class = "datepicker form-control" }, })
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Paper Submission Start Date", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PaperSubStartDateString, new { htmlAttributes = new { @class = "datepicker form-control" }, })
                @Html.ValidationMessageFor(model => model.PaperSubStartDate)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Paper Submission End Date", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PaperSubEndDateString, new { htmlAttributes = new { @class = "datepicker form-control" }, })
                @Html.ValidationMessageFor(model => model.PaperSubEndDate)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-4 col-md-8">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $.fn.datepicker.defaults.format = "dd-mm-yyyy";
            $('.datepicker').datepicker();
        });
    </script>
}

Icasie/Views/Conference/Index.cshtml
@model IEnumerable<Icasie.Models.ViewModelConference>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Conference List</h2>
@if (User.IsInRole("Administrator"))
{ 
    
<p>
    @Html.ActionLink("Add New Conference", "Create", null, new { @class = "btn btn-primary" })
</p>
}
@if (TempData["message"] != null)
{ 
        <label style="color:red;font-style:italic">@TempData["message"]</label>
}

<table id="example" class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Start Date
            </th>
            <th>
                End Date
            </th>
            <th>
                Full Paper Submission Start Date
            </th>
            <th>
                Full Paper Submission End Date
            </th>
            <th>
                Full Paper Submission Status
            </th>
            <th width="300px">Action</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>
               
            </th>
            <th>
                
            </th>
            <th>
                
            </th>
            <th>
               
            </th>
            <th>
                
            </th>
            <th>
                
            </th>
            <th></th>
        </tr>
    </tfoot>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.Raw(item.StartDate.ToString(Icasie.Helper.Constant.DateFormat))
                </td>
                <td>
                    @Html.Raw(item.EndDate.ToString(Icasie.Helper.Constant.DateFormat))
                </td>
                <td>
                    @Html.Raw(item.PaperSubStartDate.ToString(Icasie.Helper.Constant.DateFormat))
                </td>
                <td>
                    @Html.Raw(item.PaperSubEndDate.ToString(Icasie.Helper.Constant.DateFormat))
                </td>
                <td>
                    @(item.PaperSubActive ? Html.Raw("Opened") : Html.Raw("Closed"))
                </td>
                <td>
                    @if (User.IsInRole("Format Checker"))
                    {
                        @Html.ActionLink("Format Checkers", "Index", "FormatChecker", new { id = item.ConferenceId }, new { @class = "btn btn-warning" })
                    }
                    @if (User.IsInRole("Reviewer"))
                    {
                        @Html.ActionLink("Reviews", "Index", "Reviewer", new { id = item.ConferenceId }, new { @class = "btn btn-warning" }) 
                    }
                    @if (User.IsInRole("Proof Reader"))
                    {
                        @Html.ActionLink("Proof Reads", "Index", "ProofReader", new { id = item.ConferenceId }, new { @class = "btn btn-warning" })
                    }
                    @if (User.IsInRole("Administrator"))
                    {
                        @Html.ActionLink("Assignments", "Assign", "Administration", new { id = item.ConferenceId }, new { @class = "btn btn-warning" })
                        @Html.Raw("&nbsp;");
                        @Html.ActionLink("Papers", "PaperList", "Submission", new { id = item.ConferenceId }, new { @class = "btn btn-info" })                        
                        @Html.Raw("&nbsp;");
                        @Html.ActionLink("Edit", "Edit", "Conference", new { id = item.ConferenceId }, new { @class = "btn btn-primary" })                        
                        @Html.Raw("&nbsp;");
                        @Html.ActionLink("Delete", "Delete", "Conference", new { id = item.ConferenceId }, new { @class = "btn btn-danger" })
                    }
    
                         
                </td>
            </tr>
        }

    </tbody>


</table>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#example').DataTable();
        });

    </script>
}

Icasie/Views/Conference/Payments.cshtml
@model IEnumerable<Icasie.Models.ViewModelConference>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Conference List</h2>
@if (TempData["message"] != null)
{
    <label style="color:red;font-style:italic">@TempData["message"]</label>
}

<table id="example" class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Start Date
            </th>
            <th>
                End Date
            </th>
            <th>
                Full Paper Submission Start Date
            </th>
            <th>
                Full Paper Submission End Date
            </th>
            <th>
                Full Paper Submission Status
            </th>
            <th width="300px">Action</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>

            </th>
            <th>

            </th>
            <th>

            </th>
            <th>

            </th>
            <th>

            </th>
            <th>

            </th>
            <th></th>
        </tr>
    </tfoot>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.Raw(item.StartDate.ToString(Icasie.Helper.Constant.DateFormat))
                </td>
                <td>
                    @Html.Raw(item.EndDate.ToString(Icasie.Helper.Constant.DateFormat))
                </td>
                <td>
                    @Html.Raw(item.PaperSubStartDate.ToString(Icasie.Helper.Constant.DateFormat))
                </td>
                <td>
                    @Html.Raw(item.PaperSubEndDate.ToString(Icasie.Helper.Constant.DateFormat))
                </td>
                <td>
                    @(item.PaperSubActive ? Html.Raw("Opened") : Html.Raw("Closed"))
                </td>
                <td>
                    @if (User.IsInRole("Administrator"))
                    {
                        @Html.ActionLink("Authors Payment", "AuthorPayment", "Administration", new { id = item.ConferenceId }, new { @class = "btn btn-warning" })
                        @Html.Raw("&nbsp;");
                        @Html.ActionLink("Participants Payment", "ParticipantPayment", "Administration", new { id = item.ConferenceId }, new { @class = "btn btn-info" })
                        
                    }


                </td>
            </tr>
        }

    </tbody>


</table>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#example').DataTable();
        });

    </script>
}