Icasie/Controllers/SubmissionController.cs
using Icasie.Helper;
using Icasie.Models;
using Icasie.Repositories;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Icasie.Controllers
{
    [Authorize]
    public class SubmissionController : Controller
    {
        //
        // GET: /Submission/
        [Authorize(Roles = "Author, Administrator, Reviewer")]
        public ActionResult Index()
        {
            //get user credential
            string currentUserEmail = HttpContext.User.Identity.Name;

            List<ViewModelConference> confList = new List<ViewModelConference>(); 

            using (IcasieEntities entity = new IcasieEntities())
            {
                var user = entity.Users.SingleOrDefault(c => c.Email == currentUserEmail);
                int userId = user.UserId;

                var subThemes = entity.SubThemes.ToList();

                var conference = entity.Conferences.ToList();                

                foreach (var item in conference)
                {
                    ViewModelConference newConf = new ViewModelConference();
                    newConf.PaperSubActive = false;

                    if (item.PaperSubStartDate <= DateTime.Now && item.PaperSubEndDate >= DateTime.Now)
                    {
                        newConf.PaperSubActive = true;
                    }

                    //fill the properties
                    newConf.ConferenceId = item.ConferenceId;
                    newConf.Name = item.Name;
                    newConf.StartDate = item.StartDate;
                    newConf.EndDate = item.EndDate;
                    newConf.PaperSubStartDate = item.PaperSubStartDate;
                    newConf.PaperSubEndDate = item.PaperSubEndDate;
                    newConf.Submissions = new List<ViewModelSubmission>();

                    var submissions = entity.Submissions.Where(c => c.UserId == userId && c.ConferenceId == item.ConferenceId);
                    foreach (var subItem in submissions)
                    {
                        ViewModelSubmission newSubmission = new ViewModelSubmission();
                        newSubmission.UserId = subItem.UserId;
                        newSubmission.ConferenceId = subItem.ConferenceId;
                        newSubmission.FullPaperStatus = subItem.FullPaperStatus;
                        newSubmission.FullPaperDate = subItem.FullPaperDate;
                        newSubmission.PaymentDate = subItem.PaymentDate;
                        newSubmission.Comment = subItem.Comment;
                        newSubmission.Title = subItem.Title;
                        newSubmission.SubmissionId = subItem.SubmissionId;
                        newSubmission.Number = subItem.PaperNumber;
                        newSubmission.SubThemesId = subItem.SubThemesId;
                        newSubmission.SubThemes = subThemes.FirstOrDefault(c => c.SubThemesId == subItem.SubThemesId).Title;
                        newSubmission.PaymentTypeString = subItem.PaymentType == Constant.PaymentType.Full ? Constant.PaymentType.FullString : Constant.PaymentType.PartialString;
                        newSubmission.PaymentType = subItem.PaymentType;
                        newSubmission.CoAuthors = subItem.CoAuthors;
                        newSubmission.TotalPayment = subItem.TotalPayment.Value;

                        if(subItem.ReviewedBy != null)
                        {   
                            var reviewer = entity.Users.SingleOrDefault(c => c.UserId == subItem.ReviewedBy);
                            newSubmission.ReviewerName = reviewer.FirstName + " " + reviewer.LastName;
                            newSubmission.FullPaperReviewFileName = subItem.FullPaperReviewFileName;
                            newSubmission.FullPaperReviewFileName2 = subItem.FullPaperReviewFileName2;
                            newSubmission.FullPaperReviewFileName3 = subItem.FullPaperReviewFileName3;
                        }

                        if (subItem.ProofReaderId != null)
                        {
                            var proofReader = entity.Users.SingleOrDefault(c => c.UserId == subItem.ProofReaderId);
                            newSubmission.ProofReaderName = proofReader.FirstName + " " + proofReader.LastName;
                            newSubmission.ProofReaderResultFileName = subItem.ProofReadingResultFileName;
                        }

                        if (subItem.FormatCheckerId != null)
                        {
                            var formatChecker = entity.Users.SingleOrDefault(c => c.UserId == subItem.FormatCheckerId);
                            newSubmission.FormatCheckerName = formatChecker.FirstName + " " + formatChecker.LastName;
                            newSubmission.FormatCheckingResultFileName = subItem.FormatCheckingResultFileName;
                        }


                        newSubmission.ReviewDateString = subItem.ReviewDate.HasValue ? subItem.ReviewDate.Value.ToString(Constant.DateFormat) : string.Empty;
                        newSubmission.ProofReadingDateString = subItem.ProofReadingDate.HasValue ? subItem.ProofReadingDate.Value.ToString(Constant.DateFormat) : string.Empty;
                        newSubmission.FormatCheckingDateString = subItem.FormatCheckingDate.HasValue ? subItem.FormatCheckingDate.Value.ToString(Constant.DateFormat) : string.Empty;  

                        newConf.Submissions.Add(newSubmission);
                    }

                    confList.Add(newConf);

                }


            }
            return View(confList);
        }


        [Authorize(Roles = "Author, Administrator, Reviewer")]
        public ActionResult EditFullPaper(int id)
        {
            ViewModelSubmission sub = new ViewModelSubmission();
            using (IcasieEntities entity = new IcasieEntities())
            {
                var oldSub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                sub.SubmissionId = oldSub.SubmissionId;
                sub.Title = oldSub.Title;
                sub.SubThemesId = oldSub.SubThemesId;
                sub.CoAuthors = oldSub.CoAuthors;
                sub.PaymentType = oldSub.PaymentType;
                sub.FullPaperStatus = oldSub.FullPaperStatus;

                PrepareViewData(entity);
            }

            PrepareSelectList();

            return View(sub);
        }

        [Authorize(Roles = "Author, Administrator, Proof Reader")]
        public ActionResult EditProofReading(int id)
        {
            ViewModelSubmission sub = new ViewModelSubmission();
            using (IcasieEntities entity = new IcasieEntities())
            {
                var oldSub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                sub.SubmissionId = oldSub.SubmissionId;
                sub.Title = oldSub.Title;
                sub.SubThemesId = oldSub.SubThemesId;
            }
            PrepareSelectList();
            return View(sub);
        }

        [HttpPost]
        [Authorize(Roles = "Author, Administrator, Proof Reader")]
        public ActionResult EditProofReading(int id, HttpPostedFileBase file)
        {
            if (file == null)
            {
                ModelState.AddModelError("file", "File cannot be empty");

                ViewModelSubmission sub = new ViewModelSubmission();
                using (IcasieEntities entity = new IcasieEntities())
                {
                    var oldSub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                    sub.SubmissionId = oldSub.SubmissionId;
                    sub.Title = oldSub.Title;
                    sub.SubThemesId = oldSub.SubThemesId;
                }

                PrepareSelectList();

                return View(sub);
            }

            using (IcasieEntities entity = new IcasieEntities())
            {
                var sub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                sub.FullPaperStatus = Constant.FullPaperStatus.Reviewed;
                sub.ProofReadingDate = null;
                sub.ProofReadingResultFileName = null;
                sub.ProofReadingResult = null;
                sub.Comment = Constant.InitialCommentProofRead;
                
                if (file != null)
                {
                    using (Stream inputStream = file.InputStream)
                    {
                        MemoryStream memoryStream = inputStream as MemoryStream;
                        if (memoryStream == null)
                        {
                            memoryStream = new MemoryStream();
                            inputStream.CopyTo(memoryStream);
                        }
                        sub.FullPaper = memoryStream.ToArray();
                        sub.FullPaperFileName = file.FileName;
                    }
                }


                entity.SaveChanges();
            }

            return RedirectToAction("Index");
        }


        [Authorize(Roles="Administrator")]
        public ActionResult PaperList(int id)
        {
            List<ViewModelSubmission> results = new List<ViewModelSubmission>();
            using (IcasieEntities entity = new IcasieEntities())
            {
                var conference = entity.Conferences.SingleOrDefault(c => c.ConferenceId == id);
                ViewData["ConferenceName"] = conference.Name;

                var submissions = entity.Submissions.Where(c => c.ConferenceId == id).OrderBy(c => c.FullPaperDate);
                foreach (var subItem in submissions)
                {
                    ViewModelSubmission newSubmission = new ViewModelSubmission();

                    var user = entity.Users.SingleOrDefault(c => c.UserId == subItem.UserId);

Icasie/Views/Submission/AddFullPaper.cshtml
@model Icasie.Models.ViewModelSubmission

@{
    ViewBag.Title = "Add Full Paper";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Full Paper</h2>


@using (Html.BeginForm("AddFullPaper", "Submission", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
               
        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" }, })
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Sub Theme", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SubThemesId, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubThemesId)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Upload Fullpaper", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file">
                    <input accept="application/pdf" name="file" id="file" type="file" /> 
                </label>             
                <br />@Html.ValidationMessage("file")
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Co Authors", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CoAuthors, new { htmlAttributes = new { @class = "form-control payment-control", @type="number", @min="0", @value="0" }, })
                @Html.ValidationMessageFor(model => model.CoAuthors)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Payment Type", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="radio" class="payment-control" id="paymentType" name="paymentType" value="1" checked> Conference & IOP Proceeding<br>
                <input type="radio" class="payment-control" id="paymentType" name="paymentType" value="2"> Conference & Icasie Proceeding<br>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Total Payment", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span id="total-payment" style="color:green;font-weight:bold">US$ 0</span> @if (ViewData["IsIndonesian"] == "false") { <span style="color:red" id="total-payment-idr"></span> }
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Upload Payment Evidence", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file">
                    <input accept="application/pdf" name="payment" id="payment" type="file" />
                </label>
                <br />@Html.ValidationMessage("payment")
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Terms & Agreement", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.TermsAgreement)
                @Html.ValidationMessageFor(model => model.TermsAgreement) <br />
                I have read this <span style="color:red"><a href="/Content/IOPPolicies.pdf">"Conference & IOP Proceeding"</a></span> and <span style="color:red"><a href="/Content/IcasiePolicies.pdf">"Conference & Icasie Proceeding"</a></span> agreement pertaining to conference rules. I agree to obey all policies, and will reference the ICASIE 2017 website (http://www.icasie.its.ac.id/) for additional guidance on paper submission regulations and policies.

</div>
        </div>
        @Html.Hidden("id", ViewData["ConferenceId"])

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#CoAuthors').val("0");
            $(".payment-control").change(function () {
                calculateAmount();
            });

            calculateAmount();
        });

        function calculateAmount()
        {
            var full = parseFloat("@ViewData["Full"]");
            var seminar = parseFloat("@ViewData["Seminar"]");
            var coauthor = parseFloat("@ViewData["Coauthor"]");

            var total = 0;

            if ($('input[name=paymentType]:checked').val() == "1") {
                total += full;
            }
            else {
                total += seminar;
            }
            
            total += (coauthor * $("#CoAuthors").val());

            $("#total-payment").text("US$ " + total.toString());

            if ("@ViewData["IsIndonesian"]" == "false") {
                $("#total-payment-idr").text("(IDR$ " + (total * @Icasie.Helper.Constant.ExchangeRate).toString() + ", Exchange Rate: IDR " + @Icasie.Helper.Constant.ExchangeRate.ToString() + " = 1 USD)");
            }
        }

    </script>

}

Icasie/Views/Submission/EditFullPaper.cshtml
@model Icasie.Models.ViewModelSubmission

@{
    ViewBag.Title = "Edit Paper";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Full Paper</h2>


@using (Html.BeginForm("EditFullPaper", "Submission", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" }, })
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Sub Theme", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SubThemesId, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubThemesId)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Upload Paper", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file">
                    <input accept="application/pdf" name="file" id="file" type="file" />
                </label>
                <br />@Html.ValidationMessage("file")
            </div>
        </div>
        @if (Model.FullPaperStatus.Equals(Icasie.Helper.Constant.FullPaperStatus.Pending))
        { 
            <div class="form-group">
                @Html.Label("Co Authors", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CoAuthors, new { htmlAttributes = new { @class = "form-control payment-control", @type = "number", @value = "0" }, })
                    @Html.ValidationMessageFor(model => model.CoAuthors)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Payment Type", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="radio" class="payment-control" id="paymentType" name="paymentType" value="1"> Conference & IOP Proceeding<br>
                    <input type="radio" class="payment-control" id="paymentType" name="paymentType" value="2"> Conference & Icasie Proceeding<br>
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Total Payment", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <span id="total-payment" style="color:green;font-weight:bold">US$ 0</span>
                </div>
            </div>
        }
        
        @Html.Hidden("id", Model.SubmissionId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('input[name=paymentType][value=@Model.PaymentType]').prop('checked', 'checked');

            $(".payment-control").change(function () {
                calculateAmount();
            });

            calculateAmount();
        });

        function calculateAmount()
        {
            var full = parseFloat("@ViewData["Full"]");
            var seminar = parseFloat("@ViewData["Seminar"]");
            var coauthor = parseFloat("@ViewData["Coauthor"]");

            var total = 0;

            if ($('input[name=paymentType]:checked').val() == "1") {
                total += full;
            }
            else {
                total += seminar;
            }
            
            total += (coauthor * $("#CoAuthors").val());

            $("#total-payment").text("US$ " + total.toString());
        }

    </script>

}

Icasie/Views/Submission/EditProofReading.cshtml
@model Icasie.Models.ViewModelSubmission

@{
    ViewBag.Title = "Edit Paper";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Proof Read</h2>


@using (Html.BeginForm("EditProofReading", "Submission", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @readonly="readonly" }, })
                
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Sub Theme", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SubThemesId, null, new { @class = "form-control", @disabled="disabled" })
                
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Upload Paper", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file">
                    <input accept="application/pdf" name="file" id="file" type="file" />
                </label>
                <br />@Html.ValidationMessage("file")
            </div>
        </div>
        @Html.Hidden("id", Model.SubmissionId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
           
        });

    </script>

}

Icasie/Views/Submission/Index.cshtml
@model IEnumerable<Icasie.Models.ViewModelConference>

@{
    ViewBag.Title = "Submission List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1>Submissions</h1>
</div>


@foreach (var item in Model)
{
    <div class="row">
        <h3 style="font-style:italic">@item.Name</h3>

        @if (item.PaperSubActive == true)
        {
            <a href="/Submission/AddFullPaper/@item.ConferenceId" class="btn btn-primary">Add Paper</a>
        }
        else
        {
            <label style="color:red;font-weight:bold">Full Paper Submission has been closed</label>
        }
        <br />
        <br />
        <table id="example" class="table table-striped table-result">
            <thead>
                <tr>
                    <th>
                        Number
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Sub Theme
                    </th>
                    <th>
                        Payment Type
                    </th>
                    <th>
                        Co Authors
                    </th>
                    <th>
                        Total Payment
                    </th>
                    <th>
                        Full Paper
                    </th>
                    <th>
                        Full Paper Upload Date
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Format Checking Result
                    </th>
                    <th>
                        Format Checker
                    </th>
                    <th>
                        Format Checker Date
                    </th>
                    <th>
                        Review Result
                    </th>
                    <th>
                        Review Result 2
                    </th>
                    <th>
                        Review Result 3
                    </th>
                    <th>
                        Reviewer
                    </th>
                    <th>
                        Review Date
                    </th>
                    <th>
                        Proof Reading Result
                    </th>
                    <th>
                        Proof Reader
                    </th>
                    <th>
                        Proof Reading Date
                    </th>
                    <th>
                        Comment
                    </th>
                    <th>
                        Payment
                    </th>
                    <th>
                        Payment Date
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var abs in item.Submissions)
                {
                    <tr>
                        <td>@abs.Number</td>
                        <td>@abs.Title</td>
                        <td>@abs.SubThemes</td>
                        <td>@abs.PaymentTypeString</td>
                        <td>@abs.CoAuthors</td>
                        <td>@abs.TotalPayment</td>
                        <td><a class="btn btn-primary" href="/Submission/Download/@abs.SubmissionId?type=@Icasie.Helper.Constant.DownloadType.FullPaper">View</a></td>
                        <td>@abs.FullPaperDate.Value.ToString(Icasie.Helper.Constant.DateFormat)</td>
                        <td>@(abs.FullPaperStatus == Icasie.Helper.Constant.FullPaperStatus.Accepted ? Html.Raw("<font style='color:green;font-weight:bold'>" + abs.FullPaperStatus + "</font>") : Html.Raw(abs.FullPaperStatus))</td>
                        <td>@((abs.FormatCheckingResultFileName == null) ? Html.Raw("") : Html.ActionLink("View", "Download", "Submission", new { @id = abs.SubmissionId, @type = Icasie.Helper.Constant.DownloadType.FormatChecking }, new { @class = "btn btn-primary" }))</td>
                        <td>@abs.FormatCheckerName</td>
                        <td>@abs.FormatCheckingDateString</td>
                        <td>@((abs.FullPaperReviewFileName == null) ? Html.Raw("") : Html.ActionLink("View", "Download", "Submission", new { @id = abs.SubmissionId, @type = Icasie.Helper.Constant.DownloadType.Review }, new { @class = "btn btn-primary" }))</td>
                        <td>@((abs.FullPaperReviewFileName2 == null) ? Html.Raw("") : Html.ActionLink("View", "Download", "Submission", new { @id = abs.SubmissionId, @type = Icasie.Helper.Constant.DownloadType.Review2 }, new { @class = "btn btn-primary" }))</td>
                        <td>@((abs.FullPaperReviewFileName3 == null) ? Html.Raw("") : Html.ActionLink("View", "Download", "Submission", new { @id = abs.SubmissionId, @type = Icasie.Helper.Constant.DownloadType.Review3 }, new { @class = "btn btn-primary" }))</td>
                        <td>@abs.ReviewerName</td>
                        <td>@abs.ReviewDateString</td>
                        <td>@((abs.ProofReaderResultFileName == null) ? Html.Raw("") : Html.ActionLink("View", "Download", "Submission", new { @id = abs.SubmissionId, @type = Icasie.Helper.Constant.DownloadType.ProofReading }, new { @class = "btn btn-primary" }))</td>
                        <td>@abs.ProofReaderName</td>
                        <td>@abs.ProofReadingDateString</td>
                        <td>@abs.Comment</td>
                        <td>@((abs.PaymentDate.HasValue) ? Html.ActionLink("View", "Download", "Submission", new { @id = abs.SubmissionId, @type = Icasie.Helper.Constant.DownloadType.Payment }, new { @class = "btn btn-primary" }) : Html.Raw(""))</td>
                        <td>@((abs.PaymentDate.HasValue) ? Html.Raw(abs.PaymentDate.Value.ToString(Icasie.Helper.Constant.DateFormat)) : Html.Raw(""))</td>
                        <td>
                            @if (abs.FullPaperStatus == Icasie.Helper.Constant.FullPaperStatus.Pending || abs.FullPaperStatus == Icasie.Helper.Constant.FullPaperStatus.FormatRevised || abs.FullPaperStatus == Icasie.Helper.Constant.FullPaperStatus.Revised)
                            {
                                <a class="btn btn-primary" href="/Submission/EditFullPaper/@abs.SubmissionId">Change</a>
                            }
                            else if (abs.FullPaperStatus == Icasie.Helper.Constant.FullPaperStatus.ProofReadingRevised)
                            {
                                <a class="btn btn-primary" href="/Submission/EditProofReading/@abs.SubmissionId">Change</a>
                            }

                    </td>
                </tr>
                }
            </tbody>

        </table>

    </div>
}

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.table-result').DataTable();
        });

    </script>
}

Icasie/Views/Submission/SubmitPayment.cshtml
@model Icasie.Models.ViewModelSubmission

@{
    ViewBag.Title = "Review Paper";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Full Paper</h2>


@using (Html.BeginForm("SubmitPayment", "Submission", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
       
        <div class="form-group">
            @Html.Label("Upload Payment Evidence", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file">
                    <input accept="application/pdf" name="payment" id="payment" type="file" />
                </label>
                <br />@Html.ValidationMessage("payment")
            </div>
        </div>
        @Html.Hidden("id", Model.SubmissionId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}