Icasie/Controllers/ProofReaderController.cs
using Icasie.Helper;
using Icasie.Models;
using Icasie.Repositories;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Icasie.Controllers
{
    [Authorize(Roles = "Proof Reader, Administrator")]
    public class ProofReaderController : Controller
    {

        public ActionResult Index(int id)
        {
            List<ViewModelConference> confList = new List<ViewModelConference>();
            //get user credential
            string currentUserEmail = HttpContext.User.Identity.Name;

            using (IcasieEntities entity = new IcasieEntities())
            {
                var conference = entity.Conferences.Where(c => c.ConferenceId == id).ToList();

                var subThemes = entity.SubThemes.ToList();

                var proofReaderId = entity.Users.SingleOrDefault(c => c.Email == currentUserEmail);

                foreach (var item in conference)
                {
                    ViewModelConference newConf = new ViewModelConference();
                    newConf.PaperSubActive = false;

                    if (item.PaperSubStartDate <= DateTime.Now && item.PaperSubEndDate >= DateTime.Now)
                    {
                        newConf.PaperSubActive = true;
                    }

                    //fill the properties
                    newConf.ConferenceId = item.ConferenceId;
                    newConf.Name = item.Name;
                    newConf.StartDate = item.StartDate;
                    newConf.EndDate = item.EndDate;
                    newConf.PaperSubStartDate = item.PaperSubStartDate;
                    newConf.PaperSubEndDate = item.PaperSubEndDate;
                    newConf.Submissions = new List<ViewModelSubmission>();

                    var submissions = entity.Submissions.Where(c => c.ConferenceId == item.ConferenceId && c.ProofReaderId == proofReaderId.UserId && (c.FullPaperStatus == Constant.FullPaperStatus.Reviewed || c.FullPaperStatus == Constant.FullPaperStatus.ProofReadingRevised));
                    foreach (var subItem in submissions)
                    {
                        ViewModelSubmission newSubmission = new ViewModelSubmission();
                        newSubmission.UserId = subItem.UserId;

                        var user = entity.Users.SingleOrDefault(c => c.UserId == newSubmission.UserId);

                        newSubmission.AuthorName = user.FirstName + " " + user.LastName;
                        newSubmission.ConferenceId = subItem.ConferenceId;
                        newSubmission.FullPaperStatus = subItem.FullPaperStatus;
                        newSubmission.FullPaper = subItem.FullPaper;
                        newSubmission.FullPaperDate = subItem.FullPaperDate;
                        newSubmission.FullPaperFileName = subItem.FullPaperFileName;
                        newSubmission.Title = subItem.Title;
                        newSubmission.SubmissionId = subItem.SubmissionId;
                        newSubmission.Number = subItem.PaperNumber;
                        newSubmission.SubThemesId = subItem.SubThemesId;
                        newSubmission.SubThemes = subThemes.FirstOrDefault(c => c.SubThemesId == subItem.SubThemesId).Title;


                        if (subItem.ProofReaderId != null)
                        {
                            var proofReader = entity.Users.SingleOrDefault(c => c.UserId == subItem.ProofReaderId);
                            newSubmission.ProofReaderName = proofReader.FirstName + " " + proofReader.LastName;
                            newSubmission.ProofReaderResultFileName = subItem.ProofReadingResultFileName;
                        }


                        newSubmission.ProofReadingDateString = subItem.ProofReadingDate.HasValue ? subItem.ProofReadingDate.Value.ToString(Constant.DateFormat) : string.Empty;

                        newConf.Submissions.Add(newSubmission);
                    }

                    confList.Add(newConf);

                }


            }
            return View(confList);
        }

        public ActionResult Edit(int id)
        {
            ViewModelSubmission sub = new ViewModelSubmission();
            using (IcasieEntities entity = new IcasieEntities())
            {
                var oldSub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                sub.SubmissionId = oldSub.SubmissionId;
                sub.ConferenceId = oldSub.ConferenceId;
                sub.Title = oldSub.Title;
            }
            return View(sub);
        }

        [HttpPost]
        public ActionResult Edit(int id, string fullPaperStatus, string comment, HttpPostedFileBase file)
        {
            int conferenceId = 0;
            if (fullPaperStatus == Constant.FullPaperStatus.ProofReadingRevised && file == null)
            {
                ModelState.AddModelError("file", "File cannot be empty");
            }

            if (fullPaperStatus == Constant.FullPaperStatus.ProofReadingRevised)
            {
                if (comment == null || comment == string.Empty)
                {
                    ModelState.AddModelError("comment", "Comment is required");
                }
            }

            if (!ModelState.IsValid)
            {
                ViewModelSubmission sub = new ViewModelSubmission();
                using (IcasieEntities entity = new IcasieEntities())
                {
                    var oldSub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                    sub.SubmissionId = oldSub.SubmissionId;
                    sub.Title = oldSub.Title;
                    sub.FullPaperStatus = fullPaperStatus;
                    sub.Comment = comment;
                }

                return View(sub);
            }

            try
            {
                using (IcasieEntities entity = new IcasieEntities())
                {
                    var sub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                    sub.Comment = comment;
                    sub.FullPaperStatus = fullPaperStatus;
                    conferenceId = sub.ConferenceId;

                    sub.ProofReadingDate = DateTime.Now;

                    string currentUserEmail = HttpContext.User.Identity.Name;

                    int userId = entity.Users.SingleOrDefault(c => c.Email == currentUserEmail).UserId;

                    sub.ProofReaderId = userId;

                    if (fullPaperStatus == Constant.FullPaperStatus.Accepted)
                    {
                        sub.ProofReadingResult = null;
                        sub.ProofReadingResultFileName = null;
                    }
                    else
                    {

                        if (file != null)
                        {
                            using (Stream inputStream = file.InputStream)
                            {
                                MemoryStream memoryStream = inputStream as MemoryStream;
                                if (memoryStream == null)
                                {
                                    memoryStream = new MemoryStream();
                                    inputStream.CopyTo(memoryStream);
                                }
                                sub.ProofReadingResult = memoryStream.ToArray();
                                sub.ProofReadingResultFileName = file.FileName;
                            }
                        }


                    }


                    entity.SaveChanges();
                }
            }
            catch (DbEntityValidationException ex)
            {
            }


            return RedirectToAction("Index", new { id = conferenceId });
        }

    }
}

Icasie/Controllers/ReviewerController.cs
using Icasie.Helper;
using Icasie.Models;
using Icasie.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Validation;
using System.Threading.Tasks;

namespace Icasie.Controllers
{
    [Authorize(Roles = "Reviewer, Administrator")]
    public class ReviewerController : Controller
    {
        //
        // GET: /Reviewer/
        public ActionResult Index(int id)
        {
            List<ViewModelConference> confList = new List<ViewModelConference>();
            //get user credential
            string currentUserEmail = HttpContext.User.Identity.Name;

            using (IcasieEntities entity = new IcasieEntities())
            {
                var conference = entity.Conferences.Where(c => c.ConferenceId == id).ToList();

                var subThemes = entity.SubThemes.ToList();

                var reviewerId = entity.Users.SingleOrDefault(c => c.Email == currentUserEmail);

                foreach (var item in conference)
                {
                    ViewModelConference newConf = new ViewModelConference();
                    newConf.PaperSubActive = false;

                    if (item.PaperSubStartDate <= DateTime.Now && item.PaperSubEndDate >= DateTime.Now)
                    {
                        newConf.PaperSubActive = true;
                    }

                    //fill the properties
                    newConf.ConferenceId = item.ConferenceId;
                    newConf.Name = item.Name;
                    newConf.StartDate = item.StartDate;
                    newConf.EndDate = item.EndDate;
                    newConf.PaperSubStartDate = item.PaperSubStartDate;
                    newConf.PaperSubEndDate = item.PaperSubEndDate;
                    newConf.Submissions = new List<ViewModelSubmission>();

                    var submissions = entity.Submissions.Where(c => c.ConferenceId == item.ConferenceId && c.ReviewedBy == reviewerId.UserId && (c.FullPaperStatus == Constant.FullPaperStatus.FormatChecked || c.FullPaperStatus == Constant.FullPaperStatus.Revised));
                    foreach (var subItem in submissions)
                    {
                        ViewModelSubmission newSubmission = new ViewModelSubmission();
                        newSubmission.UserId = subItem.UserId;

                        var user = entity.Users.SingleOrDefault(c => c.UserId == newSubmission.UserId);

                        newSubmission.AuthorName = user.FirstName + " " + user.LastName;
                        newSubmission.ConferenceId = subItem.ConferenceId;
                        newSubmission.FullPaperStatus = subItem.FullPaperStatus;
                        newSubmission.FullPaper = subItem.FullPaper;
                        newSubmission.FullPaperDate = subItem.FullPaperDate;
                        newSubmission.FullPaperFileName = subItem.FullPaperFileName;
                        newSubmission.Payment = subItem.Payment;
                        newSubmission.PaymentDate = subItem.PaymentDate;
                        newSubmission.PaymentFileName = subItem.PaymentFileName;
                        newSubmission.Comment = subItem.Comment;
                        newSubmission.Title = subItem.Title;
                        newSubmission.SubmissionId = subItem.SubmissionId;
                        newSubmission.FullPaperReview = subItem.FullPaperReview;
                        newSubmission.FullPaperReviewFileName = subItem.FullPaperReviewFileName;
                        newSubmission.Number = subItem.PaperNumber;
                        newSubmission.SubThemesId = subItem.SubThemesId;
                        newSubmission.SubThemes = subThemes.FirstOrDefault(c => c.SubThemesId == subItem.SubThemesId).Title;


                        if (subItem.ReviewedBy != null)
                        {
                            var reviewer = entity.Users.SingleOrDefault(c => c.UserId == subItem.ReviewedBy);
                            newSubmission.ReviewerName = reviewer.FirstName + " " + reviewer.LastName;
                            newSubmission.FullPaperReviewFileName = subItem.FullPaperReviewFileName;
                            newSubmission.FullPaperReviewFileName2 = subItem.FullPaperReviewFileName2;
                            newSubmission.FullPaperReviewFileName3 = subItem.FullPaperReviewFileName3;
                        }


                        newSubmission.ReviewDateString = subItem.ReviewDate.HasValue ? subItem.ReviewDate.Value.ToString(Constant.DateFormat) : string.Empty;

                        newConf.Submissions.Add(newSubmission);
                    }

                    confList.Add(newConf);

                }


            }
            return View(confList);
        }

        public ActionResult Edit(int id)
        {
            ViewModelSubmission sub = new ViewModelSubmission();
            using (IcasieEntities entity = new IcasieEntities())
            {
                var oldSub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                sub.SubmissionId = oldSub.SubmissionId;
                sub.ConferenceId = oldSub.ConferenceId;
                sub.Title = oldSub.Title;
            }
            return View(sub);
        }

        [HttpPost]
        public ActionResult Edit(int id, string fullPaperStatus, string comment, HttpPostedFileBase file, HttpPostedFileBase file2, HttpPostedFileBase file3)
        {
            int conferenceId = 0;
            var conferenceName = string.Empty;
            var paperTitle = string.Empty;
            List<string> proofReaderEmail = new List<string>();

            if (fullPaperStatus == Constant.FullPaperStatus.Revised && file == null)
            {
                ModelState.AddModelError("file", "File cannot be empty");
            }

            if (fullPaperStatus == Constant.FullPaperStatus.Revised || fullPaperStatus == Constant.FullPaperStatus.Rejected)
            {
                if (comment == null || comment == string.Empty)
                {
                    ModelState.AddModelError("comment", "Comment is required");
                }
            }

            if (!ModelState.IsValid)
            {
                ViewModelSubmission sub = new ViewModelSubmission();
                using (IcasieEntities entity = new IcasieEntities())
                {
                    var oldSub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                    sub.SubmissionId = oldSub.SubmissionId;
                    sub.Title = oldSub.Title;
                    sub.FullPaperStatus = fullPaperStatus;
                    sub.Comment = comment;
                }

                return View(sub);
            }

            try
            {
                using (IcasieEntities entity = new IcasieEntities())
                {
                    var sub = entity.Submissions.SingleOrDefault(c => c.SubmissionId == id);
                    sub.Comment = comment;
                    sub.FullPaperStatus = fullPaperStatus;
                    conferenceId = sub.ConferenceId;

                    sub.ReviewDate = DateTime.Now;

                    string currentUserEmail = HttpContext.User.Identity.Name;

                    int userId = entity.Users.SingleOrDefault(c => c.Email == currentUserEmail).UserId;

                    sub.ReviewedBy = userId;

                    if (fullPaperStatus == Constant.FullPaperStatus.Rejected || fullPaperStatus == Constant.FullPaperStatus.Reviewed)
                    {
                        sub.FullPaperReview = null;
                        sub.FullPaperReviewFileName = null;
                        sub.FullPaperReview2 = null;
                        sub.FullPaperReviewFileName2 = null;
                        sub.FullPaperReview3 = null;
                        sub.FullPaperReviewFileName3 = null;
                    }
                    else
                    {

                        if (file != null)
                        {
                            using (Stream inputStream = file.InputStream)
                            {
                                MemoryStream memoryStream = inputStream as MemoryStream;
                                if (memoryStream == null)
                                {
                                    memoryStream = new MemoryStream();
                                    inputStream.CopyTo(memoryStream);
                                }
                                sub.FullPaperReview = memoryStream.ToArray();
                                sub.FullPaperReviewFileName = file.FileName;
                            }
                        }

                        if (file2 != null)
                        {
                            using (Stream inputStream = file2.InputStream)
                            {
                                MemoryStream memoryStream = inputStream as MemoryStream;
                                if (memoryStream == null)
                                {
                                    memoryStream = new MemoryStream();
                                    inputStream.CopyTo(memoryStream);
                                }
                                sub.FullPaperReview2 = memoryStream.ToArray();
                                sub.FullPaperReviewFileName2 = file2.FileName;
                            }
                        }

                        if (file3 != null)
                        {
                            using (Stream inputStream = file3.InputStream)
                            {
                                MemoryStream memoryStream = inputStream as MemoryStream;
                                if (memoryStream == null)
                                {
                                    memoryStream = new MemoryStream();
                                    inputStream.CopyTo(memoryStream);

Icasie/Views/ProofReader/Edit.cshtml
@model Icasie.Models.ViewModelSubmission

@{
    ViewBag.Title = "Review Full Paper";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Proof Read Paper</h2>


@using (Html.BeginForm("Edit", "ProofReader", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Model.Title
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Status", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FullPaperStatus", Icasie.Helper.Helper.GetProofReadingStatusList(), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FullPaperStatus)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Upload Proof Reading Review Result", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file">
                    <input accept="application/pdf" name="file" id="file" type="file" />
                </label>
                <br />@Html.ValidationMessage("file")
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Comment, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comment, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Comment)
            </div>
        </div>
        @Html.Hidden("id", Model.SubmissionId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.ConferenceId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Icasie/Views/ProofReader/Index.cshtml
@model IEnumerable<Icasie.Models.ViewModelConference>

@{
    ViewBag.Title = "Review List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1>Proof Reads</h1>
</div>


@foreach (var item in Model)
{
    <div class="row">
        <h3>@item.Name</h3>
        <table class="table table-result">
            <thead>
                <tr>
                    <th>
                        Author
                    </th>
                    <th>
                        Number
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Sub Theme
                    </th>
                    <th>
                        Full Paper
                    </th>
                    <th>
                        Full Paper Upload Date
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Proof Reading Result
                    </th>
                    <th>
                        Proof Reader
                    </th>
                    <th>
                        Proof Reading Date
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                </tr>
            </tfoot>
            <tbody>
                @*<tr>
                        <td colspan="14"><h3><i>Waiting for Review</i></h3></td>
                    </tr>
                    @foreach (var abs in item.Submissions.Where(c => c.FullPaperStatus == Icasie.Helper.Constant.FullPaperStatus.Pending ))
                    {
                        <tr>
                            <td>@abs.AuthorName</td>
                            <td>@abs.Number</td>
                            <td>@abs.Title</td>
                            <td>@abs.SubThemes</td>
                            <td><a class="btn btn-primary" href="/Submission/Download/@abs.SubmissionId?type=@Icasie.Helper.Constant.DownloadType.FullPaper">View</a></td>
                            <td>@abs.FullPaperDate.Value.ToString(Icasie.Helper.Constant.DateFormat)</td>
                            <td>@abs.FullPaperStatus</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>@abs.Comment</td>
                            <td></td>
                            <td></td>
                            <td>
                                    <a class="btn btn-warning" href="/Reviewer/Edit/@abs.SubmissionId">Review</a>
                            </td>
                        </tr>
                    }
                    <tr>
                        <td colspan="14"><h3><i>Waiting for Revision</i></h3></td>
                    </tr>*@
                @foreach (var abs in item.Submissions)
                {
                    <tr>
                        <td>@abs.AuthorName</td>
                        <td>@abs.Number</td>
                        <td>@abs.Title</td>
                        <td>@abs.SubThemes</td>
                        <td><a class="btn btn-primary" href="/Submission/Download/@abs.SubmissionId?type=@Icasie.Helper.Constant.DownloadType.FullPaper">View</a></td>
                        <td>@abs.FullPaperDate.Value.ToString(Icasie.Helper.Constant.DateFormat)</td>
                        <td>@abs.FullPaperStatus</td>
                        <td>@((abs.ProofReaderResultFileName != null) ? Html.ActionLink("View", "Download", "Submission", new { @id = abs.SubmissionId, @type = Icasie.Helper.Constant.DownloadType.ProofReading }, new { @class = "btn btn-primary" }) : Html.Raw(""))</td>
                        <td>@abs.ProofReaderName</td>
                        <td>@abs.ProofReadingDateString</td>
                        <td>
                            @if (abs.FullPaperStatus.Equals(Icasie.Helper.Constant.FullPaperStatus.Reviewed))
                            {
                                <a class="btn btn-warning" href="/ProofReader/Edit/@abs.SubmissionId">Proof Read</a>
                            }
                        </td>
                    </tr>
                }
                @*<tr>
                        <td colspan="14"><h3><i>Accepted</i></h3></td>
                    </tr>
                    @foreach (var abs in item.Submissions.Where(c => c.FullPaperStatus == Icasie.Helper.Constant.FullPaperStatus.Accepted))
                    {
                        <tr>
                            <td>@abs.AuthorName</td>
                            <td>@abs.Number</td>
                            <td>@abs.Title</td>
                            <td>@abs.SubThemes</td>
                            <td><a class="btn btn-primary" href="/Submission/Download/@abs.SubmissionId?type=@Icasie.Helper.Constant.DownloadType.FullPaper">View</a></td>
                            <td>@abs.FullPaperDate.Value.ToString(Icasie.Helper.Constant.DateFormat)</td>
                            <td>@abs.FullPaperStatus</td>
                            <td></td>
                            <td>@abs.ReviewerName</td>
                            <td>@abs.ReviewDateString</td>
                            <td>@abs.Comment</td>
                            <td>@((abs.PaymentDate.HasValue) ? Html.ActionLink("View", "Download", "Submission", new { @id = abs.SubmissionId, @type = Icasie.Helper.Constant.DownloadType.Payment }, new { @class = "btn btn-primary" }) : Html.Raw(""))</td>
                            <td>@((abs.PaymentDate.HasValue) ? Html.Raw(abs.PaymentDate.Value.ToString(Icasie.Helper.Constant.DateFormat)) : Html.Raw(""))</td>
                            <td>@(abs.PaymentDate.HasValue ? Html.ActionLink("Verify Payment", "VerifyPayment", "Reviewer", new { @id = abs.SubmissionId }, new { @class = "btn btn-warning" }) : Html.Raw(""))</td>
                        </tr>
                    }

                    <tr>
                        <td colspan="14"><h3><i>Payment Verified</i></h3></td>
                    </tr>
                    @foreach (var abs in item.Submissions.Where(c => c.FullPaperStatus == Icasie.Helper.Constant.FullPaperStatus.PaymentVerified))
                    {
                        <tr>
                            <td>@abs.AuthorName</td>
                            <td>@abs.Number</td>
                            <td>@abs.Title</td>
                            <td>@abs.SubThemes</td>
                            <td><a class="btn btn-primary" href="/Submission/Download/@abs.SubmissionId?type=@Icasie.Helper.Constant.DownloadType.FullPaper">View</a></td>
                            <td>@abs.FullPaperDate.Value.ToString(Icasie.Helper.Constant.DateFormat)</td>
                            <td>@abs.FullPaperStatus</td>
                            <td></td>
                            <td>@abs.ReviewerName</td>
                            <td>@abs.ReviewDateString</td>
                            <td>@abs.Comment</td>
                            <td>@((abs.PaymentDate.HasValue) ? Html.ActionLink("View", "Download", "Submission", new { @id = abs.SubmissionId, @type = Icasie.Helper.Constant.DownloadType.Payment }, new { @class = "btn btn-primary" }) : Html.Raw(""))</td>
                            <td>@((abs.PaymentDate.HasValue) ? Html.Raw(abs.PaymentDate.Value.ToString(Icasie.Helper.Constant.DateFormat)) : Html.Raw(""))</td>
                            <td></td>
                        </tr>
                    }

                    <tr>
                        <td colspan="14"><h3><i>Rejected</i></h3></td>
                    </tr>
                    @foreach (var abs in item.Submissions.Where(c => c.FullPaperStatus == Icasie.Helper.Constant.FullPaperStatus.Rejected))
                    {
                        <tr>
                            <td>@abs.AuthorName</td>
                            <td>@abs.Number</td>
                            <td>@abs.Title</td>
                            <td>@abs.SubThemes</td>
                            <td><a class="btn btn-primary" href="/Submission/Download/@abs.SubmissionId?type=@Icasie.Helper.Constant.DownloadType.FullPaper">View</a></td>
                            <td>@abs.FullPaperDate.Value.ToString(Icasie.Helper.Constant.DateFormat)</td>
                            <td>@abs.FullPaperStatus</td>
                            <td></td>
                            <td>@abs.ReviewerName</td>
                            <td>@abs.ReviewDateString</td>
                            <td>@abs.Comment</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    }*@

            </tbody>

        </table>

    </div>
}

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.table-result').DataTable({
                initComplete: function () {
                    this.api().columns().every(function (index) {
                        if (index == 6) {
                            var column = this;
                            var select = $('<select><option value=""></option></select>')
                                .appendTo($(column.footer()).empty())
                                .on('change', function () {
                                    var val = $.fn.dataTable.util.escapeRegex(
                                        $(this).val()
                                    );

                                    column
                                        .search(val ? '^' + val + '$' : '', true, false)
                                        .draw();
                                });

                            column.data().unique().sort().each(function (d, j) {
                                select.append('<option value="' + d + '">' + d + '</option>')
                            });
                        }

                    });
                }
            });
        });

    </script>
}